
package uy.com.antel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceIMM", targetNamespace = "http://antel.com.uy/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceIMM {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "comprarTicket", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.ComprarTicket")
    @ResponseWrapper(localName = "comprarTicketResponse", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.ComprarTicketResponse")
    public String comprarTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://antel.com.uy/", className = "uy.com.antel.TestResponse")
    public String test(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
