
package uy.com.antel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceIMMService", targetNamespace = "http://antel.com.uy/", wsdlLocation = "http://localhost:8080/servlet/WebServiceIMM?wsdl")
public class WebServiceIMMService
    extends Service
{

    private final static URL WEBSERVICEIMMSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEIMMSERVICE_EXCEPTION;
    private final static QName WEBSERVICEIMMSERVICE_QNAME = new QName("http://antel.com.uy/", "WebServiceIMMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servlet/WebServiceIMM?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEIMMSERVICE_WSDL_LOCATION = url;
        WEBSERVICEIMMSERVICE_EXCEPTION = e;
    }

    public WebServiceIMMService() {
        super(__getWsdlLocation(), WEBSERVICEIMMSERVICE_QNAME);
    }

    public WebServiceIMMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEIMMSERVICE_QNAME, features);
    }

    public WebServiceIMMService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEIMMSERVICE_QNAME);
    }

    public WebServiceIMMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEIMMSERVICE_QNAME, features);
    }

    public WebServiceIMMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceIMMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceIMM
     */
    @WebEndpoint(name = "WebServiceIMMPort")
    public WebServiceIMM getWebServiceIMMPort() {
        return super.getPort(new QName("http://antel.com.uy/", "WebServiceIMMPort"), WebServiceIMM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceIMM
     */
    @WebEndpoint(name = "WebServiceIMMPort")
    public WebServiceIMM getWebServiceIMMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://antel.com.uy/", "WebServiceIMMPort"), WebServiceIMM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEIMMSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEIMMSERVICE_EXCEPTION;
        }
        return WEBSERVICEIMMSERVICE_WSDL_LOCATION;
    }

}
